#!/usr/bin/python

"""Amulet tests on a basic lxd deployment on trusty-kilo."""

from basic_deployment import LXDBasicDeployment

if __name__ == '__main__':
    deployment = LXDBasicDeployment(series='trusty',
                                    openstack='cloud:trusty-kilo',
                                    source='cloud:trusty-updates/kilo')
    deployment.run_tests()
