#!/usr/bin/env python

"""Amulet tests on a basic lxd deployment on trusty-liberty."""

from basic_deployment import LXDBasicDeployment

if __name__ == '__main__':
    deployment = LXDBasicDeployment(series='trusty',
                                    openstack='cloud:trusty-liberty',
                                    source='cloud:trusty-updates/liberty')
    deployment.run_tests()
