#!/usr/bin/env python

"""Amulet tests on a basic lxd deployment on xenial-mitaka."""

from basic_deployment import LXDBasicDeployment

if __name__ == '__main__':
    deployment = LXDBasicDeployment(
        series='xenial', openstack=None, source=None,
        stable=False)
    deployment.run_tests()
