#!/usr/bin/env python

import os
import shutil
from subprocess import check_call
import sys

from charmhelpers.core.hookenv import (
    Hooks,
    UnregisteredHookError,
    config,
    log,
    relation_set,
    relation_ids,
)

from charmhelpers.core.host import (
    adduser,
    mkdir,
    restart_on_change,
    service_start
)


from lxd_utils import (
    install_lxd,
)

hooks = Hooks()
config = config()


@hooks.hook()
def install():
    log('Instatlling LXD')
    install_lxd()

@hooks.hook('config-changed')
def config_changed():
    log('config changed')


@hooks.hook("controller-api-relation-joined")
def lxd_joined():
    log('relation joined')

@hooks.hook("upgrade-charm")
def upgrade_charm():
    pass

def main():
    try:
        hooks.execute(sys.argv)
    except UnregisteredHookError as e:
        log("Unknown hook {} - skipping.".format(e))

if __name__ == "__main__":
    main()
